package com.nala.armoire.model.dto.request;

import com.nala.armoire.model.dto.response.CustomizationConfigDTO;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.UUID;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CustomizationRequest {

    /**
     * Optional: Existing customization ID for updates
     * If provided, the service will UPDATE the existing customization
     * If null/blank, a NEW customization will be created
     */
    private String customizationId;

    /**
     * Required: Product ID being customized
     */
    @NotNull(message = "Product ID is required")
    private UUID productId;

    /**
     * Required: Complete customization configuration (canvas + layers)
     */
    @NotNull(message = "Configuration is required")
    @Valid
    private CustomizationConfigDTO configuration;

    /**
     * Required: Preview image URL (generated by frontend using Konva/Canvas)
     * High quality image (~1200x1200px) for viewing in orders and designs page
     * Frontend must generate and upload to S3/CloudFront before calling save API
     */
    @NotNull(message = "Preview image URL is required")
    private String previewImageUrl;

    /**
     * Required: Thumbnail image URL (generated by frontend)
     * Smaller image (~300x300px) for grid displays and quick previews
     * Frontend must generate and upload to S3/CloudFront before calling save API
     */
    @NotNull(message = "Thumbnail URL is required")
    private String thumbnailUrl;

    /**
     * Optional: Session ID for guest users
     * Used to associate designs with anonymous sessions before login
     * Required for guest users, null for authenticated users
     */
    private String sessionId;
}