package com.nala.armoire.model.dto.request;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.UUID;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CustomizationRequest {

    /**
     * Optional: Existing customization ID for updates
     * If provided, the service will UPDATE the existing customization
     * If null, a NEW customization will be created
     */
    private UUID id;

    /**
     * Required: Product ID being customized
     */
    @NotNull(message = "Product ID is required")
    private UUID productId;

    /**
     * Required: Variant ID (color/size variant of the product)
     */
    @NotNull(message = "Variant ID is required")
    private UUID variantId;

    /**
     * Required: Design ID (the embroidery design being applied)
     */
    @NotNull(message = "Design ID is required")
    private UUID designId;

    /**
     * Required: Thread color in hex format (#RRGGBB)
     */
    @NotNull(message = "Thread color is required")
    @Pattern(regexp = "^#[0-9A-Fa-f]{6}$", message = "Thread color must be in hex format (#RRGGBB)")
    private String threadColorHex;

    /**
     * Required: Preview image URL (generated by frontend using Konva/Canvas)
     * High quality image for viewing in orders and designs page
     * Frontend must generate and upload to S3/CloudFront before calling save API
     */
    @NotNull(message = "Preview image URL is required")
    private String previewImageUrl;

    /**
     * Optional: Additional notes or instructions for the customization
     */
    private String additionalNotes;

    /**
     * Optional: Session ID for guest users
     * Used to associate designs with anonymous sessions before login
     * Required for guest users, null for authenticated users
     */
    private String sessionId;
}
